export default [
  {
    type: 'function',
    name: 'closePosition',
    inputs: [
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: '_priceUpdateData', type: 'bytes[]', internalType: 'bytes[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'collateralToken',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'excessOpenInterest',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBorrowRate',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFundingRate',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPositionDetails',
    inputs: [
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: 'price', type: 'int256', internalType: 'int256' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct ITradePair.PositionDetails',
        components: [
          { name: 'id', type: 'uint256', internalType: 'uint256' },
          { name: 'collateral', type: 'uint256', internalType: 'uint256' },
          { name: 'entryVolume', type: 'int256', internalType: 'int256' },
          { name: 'assets', type: 'int256', internalType: 'int256' },
          { name: 'entryTimestamp', type: 'uint256', internalType: 'uint256' },
          { name: 'borrowFeeAmount', type: 'int256', internalType: 'int256' },
          { name: 'fundingFeeAmount', type: 'int256', internalType: 'int256' },
          { name: 'owner', type: 'address', internalType: 'address' },
          { name: 'direction', type: 'int8', internalType: 'int8' },
          { name: 'value', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUnrealizedPnL',
    inputs: [{ name: 'priceUpdateData_', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'liquidatePosition',
    inputs: [
      { name: 'id', type: 'uint256', internalType: 'uint256' },
      { name: '_priceUpdateData', type: 'bytes[]', internalType: 'bytes[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'maxFundingRate',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxSkew',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openPosition',
    inputs: [
      { name: 'collateral', type: 'uint256', internalType: 'uint256' },
      { name: 'leverage', type: 'uint256', internalType: 'uint256' },
      { name: 'direction', type: 'int8', internalType: 'int8' },
      { name: '_priceUpdateData', type: 'bytes[]', internalType: 'bytes[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'pyth',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IPyth' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setCloseFee',
    inputs: [{ name: 'fee', type: 'int256', internalType: 'int256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMaxFundingRate',
    inputs: [{ name: 'rate', type: 'int256', internalType: 'int256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMaxPriceAge',
    inputs: [{ name: 'maxPriceAge', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMaxSkew',
    inputs: [{ name: 'maxSkew', type: 'int256', internalType: 'int256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setOpenFee',
    inputs: [{ name: 'fee', type: 'int256', internalType: 'int256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'totalBorrowFeeIntegral',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalFundingFeeIntegral',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'unrealizedBorrowFeeIntegral',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'unrealizedFundingFeeIntegral',
    inputs: [],
    outputs: [{ name: '', type: 'int256', internalType: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'updateFeeIntegrals',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'CloseFeePaid',
    inputs: [{ name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CloseFeeSet',
    inputs: [{ name: 'closeFee', type: 'int256', indexed: false, internalType: 'int256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MaxFundingRateSet',
    inputs: [{ name: 'maxFundingRate', type: 'int256', indexed: false, internalType: 'int256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MaxPriceAgeSet',
    inputs: [{ name: 'maxPriceAge', type: 'uint256', indexed: false, internalType: 'uint256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MaxSkewSet',
    inputs: [{ name: 'maxSkew', type: 'int256', indexed: false, internalType: 'int256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OpenFeeSet',
    inputs: [{ name: 'openFee', type: 'int256', indexed: false, internalType: 'int256' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionClosed',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'id', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'value', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'closePrice', type: 'int256', indexed: false, internalType: 'int256' },
      { name: 'borrowFeeAmount', type: 'int256', indexed: false, internalType: 'int256' },
      { name: 'fundingFeeAmount', type: 'int256', indexed: false, internalType: 'int256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionLiquidated',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'id', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'borrowFeeAmount', type: 'int256', indexed: false, internalType: 'int256' },
      { name: 'fundingFeeAmount', type: 'int256', indexed: false, internalType: 'int256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionOpened',
    inputs: [
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'id', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'entryPrice', type: 'int256', indexed: false, internalType: 'int256' },
      { name: 'collateral', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'volume', type: 'int256', indexed: false, internalType: 'int256' },
      { name: 'assets', type: 'int256', indexed: false, internalType: 'int256' },
      { name: 'direction', type: 'int8', indexed: false, internalType: 'int8' },
      { name: 'borrowFeeIntegral', type: 'int256', indexed: false, internalType: 'int256' },
      { name: 'fundingFeeIntegral', type: 'int256', indexed: false, internalType: 'int256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TradePairConstructed',
    inputs: [
      { name: 'collateralToken', type: 'address', indexed: false, internalType: 'address' },
      { name: 'pyth', type: 'address', indexed: false, internalType: 'address' },
      { name: 'assetDecimals', type: 'uint8', indexed: false, internalType: 'uint8' },
      { name: 'collateralDecimals', type: 'uint8', indexed: false, internalType: 'uint8' },
      { name: 'pythId', type: 'bytes32', indexed: false, internalType: 'bytes32' },
      { name: 'name', type: 'string', indexed: false, internalType: 'string' },
    ],
    anonymous: false,
  },
] as const;
